# Generated by Django 6.0.4 on 2026-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Foto del técnico'),
        ),
    ]
