# Generated by Django 6.0.4 on 2026-04-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('tablero_control', 'Tablero de control'), ('hidrosistema', 'Hidrosistema'), ('sistema_eyector', 'Sistema eyector'), ('motor', 'Motor'), ('bombas', 'Bombas')], max_length=30, verbose_name='Sección')),
                ('parameter', models.CharField(max_length=100, verbose_name='Parámetro')),
                ('position', models.CharField(max_length=10, verbose_name='Posición')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor numérico')),
            ],
            options={
                'verbose_name': 'Valor de inspección',
                'verbose_name_plural': 'Valores de inspección',
                'ordering': ['section', 'parameter', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/photos/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de mantenimiento',
                'verbose_name_plural': 'Fotos de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('tower', models.CharField(blank=True, max_length=100, null=True, verbose_name='Torre')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número')),
                ('maintenance_type', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('asistencia_tecnica', 'Asistencia técnica'), ('emergencia', 'Emergencia')], max_length=30, verbose_name='Tipo de mantenimiento')),
                ('equipment', models.CharField(max_length=150, verbose_name='Equipo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('site', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sede')),
                ('parts_for_change', models.TextField(blank=True, null=True, verbose_name='Partes para cambio')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('general_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado general')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='clients.client')),
            ],
            options={
                'verbose_name': 'Bitácora de mantenimiento',
                'verbose_name_plural': 'Bitácoras de mantenimiento',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
