# Generated by Django 6.0.4 on 2026-04-07 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancephoto',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='inspectionvalue',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_values', to='maintenance.maintenancerecord'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionvalue',
            unique_together={('maintenance', 'section', 'parameter', 'position')},
        ),
    ]
