# Generated by Django 6.0.4 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/signatures/client/', verbose_name='Firma cliente'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='process_status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('pendiente_repuesto', 'Pendiente repuesto'), ('cerrado', 'Cerrado')], default='borrador', max_length=30, verbose_name='Estado del proceso'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='signed_by_client_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Firma cliente fecha'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='signed_by_technician_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Firma técnico fecha'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician_signature',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/signatures/technician/', verbose_name='Firma técnico'),
        ),
    ]
